### ISSUE TITLE
Patternish project doesn't work

### ISSUE THREAD

**Issue by AlvesR0** [itsmaximelau/patternish#2]
Hi! @itsmaximelau I downloaded it but it doesn't work. the screen opens and closes in the blink of an eye. I have java installed, Windows 10 64bit. Are there any extra files to make it work?

**Comment by itsmaximelau** [comment]
Hi @AlvesR0 ! You may have an older version of Java installed. I didn't specify it in the README, but you must have Java 11+ installed to run the jar correctly. I just tried with a different computer with a fresh Java install and when I tried executing the jar with Java 8, I had issues. Once I downloaded Java 11, the app opened correctly.

I hope this fixes your issue ! Have a great day :) !

**Comment by AlvesR0** [comment]
Thanks for your willingness to respond. Weird. I downloaded the latest version (installed and uninstalled java about 3 times). Still it didn't work.

**Comment by itsmaximelau** [comment]
No worries 👍 I'd be very happy if you'd be able to run it. I'd suggest that you try running the jar with the command line, to get details about the crash ! This may help with the troubleshooting !

In case you don't know how to do it, [here's a link](https://stackoverflow.com/questions/5774970/run-jar-file-in-command-prompt). Basically, you need to open your command prompt, navigate to the directory where the jar is located and run `java -jar patternish.jar`. Then, look out for any error message :).

To get the Java version problem out of the way, you may also look your current version with the follow command in a command prompt : `java -version`
